server:
  port: 5010
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: account
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/onlineordering?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
  instance:
    instance-id: account-5010
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.niit
