server:
  port: 5050
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: order
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/onlineordering?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://127.0.0.1:3306/onlineordering?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
  instance:
    instance-id: order-5050
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.niit
